main: net.limework.rediskript.RediSkript
name: ${project.name}
version: ${project.version}
authors: [Govindas, ham1255, DaemonicKing, limework.net]
api-version: 1.13
depend: [Skript]
commands:
  reloadredis:
    description: "Reload redis configuration & restart the connection."